# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1204, 703)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.IPLable = QtWidgets.QLabel(self.groupBox_6)
        self.IPLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.IPLable.setObjectName("IPLable")
        self.gridLayout_2.addWidget(self.IPLable, 0, 0, 1, 1)
        self.ServerPushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ServerPushButton.setObjectName("ServerPushButton")
        self.gridLayout_2.addWidget(self.ServerPushButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.IpLineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.IpLineEdit.setObjectName("IpLineEdit")
        self.gridLayout_2.addWidget(self.IpLineEdit, 0, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.UploadPushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.UploadPushButton.setObjectName("UploadPushButton")
        self.gridLayout_3.addWidget(self.UploadPushButton, 1, 0, 1, 1)
        self.SRPushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.SRPushButton.setObjectName("SRPushButton")
        self.gridLayout_3.addWidget(self.SRPushButton, 1, 1, 1, 1)
        self.UploadLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UploadLabel.sizePolicy().hasHeightForWidth())
        self.UploadLabel.setSizePolicy(sizePolicy)
        self.UploadLabel.setMaximumSize(QtCore.QSize(364, 364))
        self.UploadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UploadLabel.setObjectName("UploadLabel")
        self.gridLayout_3.addWidget(self.UploadLabel, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ResultLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultLabel.sizePolicy().hasHeightForWidth())
        self.ResultLabel.setSizePolicy(sizePolicy)
        self.ResultLabel.setMaximumSize(QtCore.QSize(900, 900))
        self.ResultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultLabel.setObjectName("ResultLabel")
        self.horizontalLayout_3.addWidget(self.ResultLabel)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 10, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 7, 0, 1, 1)
        self.ZoomBigPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ZoomBigPushButton.setObjectName("ZoomBigPushButton")
        self.gridLayout_4.addWidget(self.ZoomBigPushButton, 9, 0, 1, 1)
        self.ZoomSmallPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ZoomSmallPushButton.setObjectName("ZoomSmallPushButton")
        self.gridLayout_4.addWidget(self.ZoomSmallPushButton, 9, 1, 1, 1)
        self.ZoomPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ZoomPushButton.setObjectName("ZoomPushButton")
        self.gridLayout_4.addWidget(self.ZoomPushButton, 8, 0, 1, 2)
        self.SavePushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.SavePushButton.setObjectName("SavePushButton")
        self.gridLayout_4.addWidget(self.SavePushButton, 11, 0, 1, 2)
        self.DrawPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.DrawPushButton.setObjectName("DrawPushButton")
        self.gridLayout_4.addWidget(self.DrawPushButton, 6, 0, 1, 2)
        self.SR4PushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.SR4PushButton.setObjectName("SR4PushButton")
        self.gridLayout_4.addWidget(self.SR4PushButton, 4, 0, 1, 2)
        self.SR2PushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.SR2PushButton.setObjectName("SR2PushButton")
        self.gridLayout_4.addWidget(self.SR2PushButton, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_6.setTitle(_translate("Form", "连接GPU服务器"))
        self.IPLable.setText(_translate("Form", "  IP地址"))
        self.ServerPushButton.setText(_translate("Form", "确定"))
        self.groupBox_5.setTitle(_translate("Form", "上传图像"))
        self.UploadPushButton.setText(_translate("Form", "上传"))
        self.SRPushButton.setText(_translate("Form", "开始"))
        self.UploadLabel.setText(_translate("Form", "UpLoad Image"))
        self.groupBox_4.setTitle(_translate("Form", "状态栏"))
        self.groupBox_2.setTitle(_translate("Form", "结果栏"))
        self.ResultLabel.setText(_translate("Form", "超分辨结果显示"))
        self.groupBox_3.setTitle(_translate("Form", "工具栏"))
        self.ZoomBigPushButton.setText(_translate("Form", "放大"))
        self.ZoomSmallPushButton.setText(_translate("Form", "缩小"))
        self.ZoomPushButton.setText(_translate("Form", "缩放图片"))
        self.SavePushButton.setText(_translate("Form", "保存图片"))
        self.DrawPushButton.setText(_translate("Form", "画笔工具"))
        self.SR4PushButton.setText(_translate("Form", "4倍超分结果"))
        self.SR2PushButton.setText(_translate("Form", "2倍超分结果"))
        self.label_4.setText(_translate("Form", "Design by ZhengGuoqing"))

